### PR TITLE
Update .NET SOEs to support ESDK 11

### PR DESCRIPTION
**Pull request by aashislamsal**

### CODE REVIEW

**Comment by hanhansun** [comment]
Thanks @aashislamsal. Will merge this PR on July 21.

**Comment by aashislamsal** [comment]
I am working on updating screenshots and texts I will assign you after I am done.

**Comment by aashislamsal** [comment]
I guess I am done with updates. Please let me know if you see any issues.

**Comment by aashislamsal** [comment]
FYI, PR merged, @davi3690

**Pull request merged**
